services:
  calainder-server:
    build:
      context: ./calainder-server
    container_name: calainder-server
    ports:
      - "8888:8888"
    env_file:
      - ./calainder-server/.env
    depends_on:
      - calainder-ai
      - calainder-crawl
    restart: unless-stopped

  calainder-ai:
    build:
      context: ./calainder-ai
    container_name: calainder-ai
    expose:
      - "8000"
    env_file:
      - ./calainder-ai/.env
    restart: unless-stopped

  calainder-crawl:
    build:
      context: ./calainder-crawl
    container_name: calainder-crawl
    expose:
      - "9000"
    env_file:
      - ./calainder-crawl/.env
    restart: unless-stopped
